title:            Scrawlon
description:      A blog about programming and technology
baseurl: ""
url: "https://scrawlon.github.io"
disqus_shortname: scrawlon
sass:
    sass_dir: _sass
    style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Owner/author information
owner:
  name:           Scott McGrath
  avatar:         owner-avatar.jpg
  # Social networking links used in footer. Update and remove as you like.
  social_networks:
    - name:       "Twitter"
      url:        "https://twitter.com/scrawlon"
      icon:       "fa-twitter"
    - name:       "Github"
      url:        "https://github.com/scrawlon"
      icon:       "fa-github"
    - name:       "Linkedin"
      url:        "https://linkedin.com/in/scrawlon"
      icon:       "fa-linkedin"

# Internal pages/posts to include in top navigation
home:
  - title: Scrawlon
    url: /
links:
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Portfolio
    url: /portfolio/
  - title: Contact
    url: /contact/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     America/New_York
future:       true
markdown: kramdown
permalink: pretty

include:
  - .htaccess
  - js
exclude:
  - lib
  - config.rb
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js

collections:
  - slides_home
