title:            Scrawlon
description:      A blog about programming and technology
baseurl: ""
url: "https://scrawlon.github.io"
disqus_shortname: scrawlon
sass:
    sass_dir: _sass
    style: compressed

# Owner/author information
owner:
  name:           Scott McGrath
  avatar:         owner-avatar.jpg
  # Social networking links used in footer. Update and remove as you like.
  twitter:        "scrawlon"
  github:         "scrawlon"
  linkedin:       "scrawlon"

# Internal pages/posts to include in top navigation
home:
  - title: Scrawlon
    url: /
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     America/New_York
future:       true
markdown: kramdown
permalink: pretty

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
